"""planadd keyboard_eligible

Revision ID: 33a28a840d5b
Revises: 5e7ed0138132
Create Date: 2021-07-28 19:17:25.525731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a28a840d5b'
down_revision = '5e7ed0138132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('dashboard_eligible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'dashboard_eligible')
    # ### end Alembic commands ###
