"""New database

Revision ID: 45b0929e717f
Revises: a3a846296dbd
Create Date: 2021-08-13 02:45:25.030454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b0929e717f'
down_revision = 'a3a846296dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
