"""add max number

Revision ID: 5e7ed0138132
Revises: 8b2e67d2c68a
Create Date: 2021-07-27 23:16:06.179604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7ed0138132'
down_revision = '8b2e67d2c68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('max_number', sa.Integer(),default=100))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'max_number')
    # ### end Alembic commands ###
